VER-80473
vertica/vertica-nodejs pull request #1
Opened 2022-04-15 14:07 UTC by DMickens

This PR looks a bit crazy because of all the files changed. Here is a summary of what changed:

1. pg-connection-string, pg-cursor, pg-pool, pg-protocol, pg-query-stream, and pg became VConnectionString, VCursor, VPool, VProtocol, VQueryStream, and vertica-nodejs respectively. 
2. All references to those name changes in tests were updated. Variable names related to these instances were updated as well. Ex. var pg = require('pg')  ----->  var vertica = require('vertica-nodejs')
3. Updated paths in Travis continuous integration files to reflect name changes
4. Updated package.json files to reflect name changes, repository changes, author, etc.

2022-04-19 18:20 UTC, alexey-temnikov commented on packages/VConnectionString/package.json
> +  "author": "Vertica",
Shall we create a NOTICE file to attribute the original author?

2022-04-19 18:20 UTC, alexey-temnikov commented on .eslintrc
> +  "ignorePatterns": ["node_modules", "coverage", "packages/VProtocol/dist/**/*", "packages/VQueryStream/dist/**/*"],
It looks we use both -`kebab-case` and `camelCase`.  Shall we unify the naming convention for node modules? `kebab-case` is the most common for nodejs module, however, it is not a requirement.

2022-04-19 19:00 UTC, DMickens commented on packages/VConnectionString/package.json
> +  "author": "Vertica",
We certainly could, but I believe we are not required to with MIT license.

2022-04-19 19:10 UTC, DMickens commented on .eslintrc
> +  "ignorePatterns": ["node_modules", "coverage", "packages/VProtocol/dist/**/*", "packages/VQueryStream/dist/**/*"],
This change is fine with me. If going with a uniform convention I would prefer kebab-case. Probably should have just gone with this from the start. v-protocol, v-query-stream, etc are all available. I will make that update

2022-04-19 21:00 UTC, williammatherjones commented on .eslintrc
> +  "ignorePatterns": ["node_modules", "coverage", "packages/VProtocol/dist/**/*", "packages/VQueryStream/dist/**/*"],
I agree with the goal of using kebab-case

2022-04-19 21:54 UTC, jonathanl-bq approved these changes
If the other comments are addressed, then it seems fine to me. I didn't look at all 226 files though :P. I'm also assuming that you've successfully built and run the tests after the rename to make sure nothing has broken.

2022-04-20 12:13 UTC, williammatherjones requested changes
Change camelCase to kebab-case as Alexey suggested.

2022-04-25 13:47 UTC, merged